on:
  push:
    branches:
      - "main"

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: 'Build'
        shell: bash
        run: |
          echo "::group::Build"
          yarn
          yarn build
          echo "::endgroup::"

      - name: 'upload'
        uses: actions/upload-pages-artifact@v2
        with: 
          path: public/playground

      - id: deploy
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v3
        with:
          token: ${{ github.token }}